env0/templates

.gitmodules, misc/git-modules/README.md, misc/git-submodules/https/README.md, misc/git-submodules/relative/README.md, misc/git-submodules/ssh/README.md
Add examples of different types of git submoduels.  
Drop explicit ssh test due to our inability to automate it at this point.
=> Split git submodules example to https/relative repo

misc/null-resource/main.tf
This will be used in nightly scheduling tests
=> Add null-resource to templates

misc/ssm-sensitive-var/README.md, misc/ssm-sensitive-var/env0.yml, misc/ssm-sensitive-var/main.tf, misc/ssm-sensitive-var/validate.sh
Template that validates that variable `SHAG_FAKE_SECRET`'s value is `FAKE_NEWS`.
For the test to work as intended, user should create such a variable with `${ssm:...}`
=> Feat: Self hosted agent SSM variable validator

misc/remote-backend-on-s3/env0.yml
Don't delete the remote backend s3 bucket upon destroy
=> Fix: remote backend template

misc/terraform-validate-workspace/main.tf
See https://env0.slack.com/archives/CH9ND4Z6C/p1620637212179400.
=> Added template to check workspace name in `terraform validate` command

misc/null-sleep/env0.yml, misc/null-sleep/main.tf
Create template with sleep script.
sleep script by 60 seconds defualt, can change by var SLEEP_IN_SECONDS
=> Chore: create TF null-sleep

aws/github-ee/main.tf, aws/github-ee/security-group.tf, aws/github-ee/variables.tf
Add uniqueness for aws resources using gh_ee_version tf var
=> Chore: Update Github EE template to support multi server in same account

aws/k8s/agent.tf, aws/k8s/cluster.tf, aws/k8s/providers.tf, aws/k8s/variables.tf, aws/k8s/versions.tf
Add template to create EKS cluster - can use for demos or for testing 
Already with kedaless
=> Feat: add k8s installation

misc/custom-flow-tf-vars/README.md, misc/custom-flow-tf-vars/env0.yml, misc/custom-flow-tf-vars/main.tf
a template exporting a TF_VAR to `ENV0_ENV` and using it in the `.tf` file
=> Custom flow tf vars

misc/custom-flow-tf-vars/env0.yml, misc/custom-flow-tf-vars/main.tf
won't be able to destroy because TF will fail - the variable doens't exist, destroy is a different deployment
=> added the TF_VAR for destroy as well

kubernetes/hello-world/env0.yml
=> fix sed command

misc/ensure-permissions-on-tools-and-folders-for-user-node/ensure-permissions.sh
=> enabling pyhton venv for deployment service

misc/ensure-permissions-on-tools-and-folders-for-user-node/ensure-permissions.sh
=> Revert "enabling pyhton venv for deployment service"

kubernetes/hello-world/env0.yml
examples to show different ways of preparing the kubeconfig.
=> docs: kubeconfig - add additional examples

kubernetes/hello-world/env0.yml
Reverts env0/templates#118
Reverting becuase env0 yml is broken. Using <myNabketName> place holder inside shell is not working
=> Revert "docs: kubeconfig - add additional examples"

misc/vault-integration/env0.yml, misc/vault-integration/main.tf, misc/vault-integration/vault.sh
This template is used for vault integration ( would be used as template integration tests probably )
=> Feat: Add Vault Integration template

azure/demo/main.tf
Azure demo template from our [archived blueprints repo ](https://github.com/env0/blueprints/tree/azure-template/azure)started failing on IT. I moved it here and updated the version + some APIs to make it work again.
=> moved azure demo template to this repo and updated version

azure/demo/README.md
this readme was included in the old template and I forgot to migrate it
=> CHORE add README.md to azure demo template

misc/workflow-environment-basic/README.md, misc/workflow-environment-basic/env0.workflow.yml
new basic more simpler workflow template for provider
=> Chore adding new basic workflow template with 2 null TF sub environments

aws/s3-bucket/s3/s3.tf
AWS introduced a breaking change into how s3 public buckets ACL should be configured (more info here).
In this PR, I've fixed the issue by setting the right ownership control and upgrading the provider to v4 to be able to use them.
I've applied this code locally to make sure it works
=> Fix: upgrade s3 bucket module to v4.0 and use proper AWS syntax

cloudformation/hello-world/stack.yaml, misc/workflow-environment/env0.workflow.yml
Continuing #167 and #169 - seems like the CF configuration needed some more tweaking in it to work. I managed to deploy it using env0, so this one should finally work
=> Fix: CF template configuration

aws/hello-world/s3.tf
Continuing #168, there was a missing dependency between resources that introduced a race condition
Adding an explicit dependency between resources in this PR
=> Fix: hello world template

misc/workflow-environment-basic/env0.workflow.yml
reverted change to workflow template as it might cause TF provider test to fail
=> Remove workspace from workflow template

misc/ensure-permissions-on-tools-and-folders-for-user-node/ensure-permissions.sh
Run helm commands to check if it can write to folders it uses
=> Chore - helm permissions check

kubernetes/using-pulumi/Pulumi.yaml, kubernetes/using-pulumi/README.md, kubernetes/using-pulumi/env0.yml, kubernetes/using-pulumi/index.ts, kubernetes/using-pulumi/package.json, kubernetes/using-pulumi/tsconfig.json, kubernetes/using-terraform/README.md, kubernetes/using-terraform/main.tf
Adding templates that use TF and Pulumi to alter K8s resources.
=> Feat: Add templates for k8s using TF and Pulumi

pulumi/aws/hello-world/index.ts
Make api gateway with a more meaningful name than only "api"
=> Fix: rename api gw

misc/workflows/environment-alias-validation/README.md, misc/workflows/environment-alias-validation/env0.workflow.yml
new template for QAing special sign aliases
first deploy:
=> chore: new WF template for QAing special sign aliases

misc/null-fail-by-variable/README.md, misc/null-fail-by-variable/env0.yml, misc/null-fail-by-variable/main.tf
checkout misc/null-usable-based-on-env-var from workflow-integration-test-v2.1 (e87a63074a8f9b7f378189f4e245da4b2092b88f)
=> chore: checkout misc/null-usable-based-on-env-var from workflow-integration-test-v2.1

misc/workflows/workflow-with-failures/env0.workflow.yml
for Integration Tests: 
reverted the workflow file in master to contain all the nodes
=> reverted failed-workflow-file

aws/custom-remote-state-bucket/main.tf
We want to add integration tests for our BYOB flow. To do that we need to create a bucket using our module
=> Chore: Add custom RBE bucket creation template

aws/custom-remote-state-bucket/main.tf
a small fix for the external id for our bucket
=> fix custom RBE bucket external id

.gitignore, pulumi/dummy-resource/Pulumi.yaml, pulumi/dummy-resource/env0.yaml, pulumi/dummy-resource/index.ts, pulumi/dummy-resource/package-lock.json, pulumi/dummy-resource/package.json, pulumi/dummy-resource/tsconfig.json
Add a project inside the `pulumi` folder that deploys a dummy resource (similar to `null_resource` in TF)
=> Chore: Add dummy resource Pulumi project
